"""org_memory table

Revision ID: 45f9fa554d73
Revises: 20260604_0002
Create Date: 2026-06-12 01:35:39.725826
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '45f9fa554d73'
down_revision: str | Sequence[str] | None = '20260604_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('source_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_memory_created_at'), 'org_memory', ['created_at'], unique=False)
    op.create_index(op.f('ix_org_memory_kind'), 'org_memory', ['kind'], unique=False)
    op.create_index(op.f('ix_org_memory_org_id'), 'org_memory', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_memory_user_id'), 'org_memory', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_org_memory_user_id'), table_name='org_memory')
    op.drop_index(op.f('ix_org_memory_org_id'), table_name='org_memory')
    op.drop_index(op.f('ix_org_memory_kind'), table_name='org_memory')
    op.drop_index(op.f('ix_org_memory_created_at'), table_name='org_memory')
    op.drop_table('org_memory')
    # ### end Alembic commands ###
